import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Homepage</h1>
      <li>
        <Link href={"/photos-ssg"}>
          <a>Static Site Generation</a>
        </Link>
      </li>
      <li>
        <Link href={"/photos-ssr"}>
          <a>Server Side Regeneration</a>
        </Link>
      </li>
      <li>
        <Link href={"/photos-isr"}>
          <a>Incremental Site Regeneration</a>
        </Link>
      </li>
      <li>
        <Link href={"/photos-on-demand-isr"}>
          <a>On Demand Incremental Site Regeneration</a>
        </Link>
      </li>
      <li>
        <Link href={"/photos-csr"}>
          <a>Client Side Rendering</a>
        </Link>
      </li>
      <li>
        <Link href={"/photos-swr"}>
          <a>Client Side Rendering-SWR</a>
        </Link>
      </li>
    </div>
  );
}
