import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const handleClick = () => {
    console.log("order placed");
    router.push("/product");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Homepage</h1>
      <li>
        <Link href={"/photos-ssg"}>
          <a>Photos (Static Site Generation)</a>
        </Link>
      </li>
      <li>
        <Link href={"/photos-ssr"}>
          <a>Photos (Server Side Regeneration)</a>
        </Link>
      </li>
      <li>
        <Link href={"/photos-isr"}>
          <a>Photos (Incremental Site Regeneration)</a>
        </Link>
      </li>
      <li>
        <Link href={"/photos-on-demand-isr"}>
          <a>Photos (On Demand Incremental Site Regeneration)</a>
        </Link>
      </li>
      <li>
        <Link href={"/photos-csr"}>
          <a>Photos (Client Side Regeneration)</a>
        </Link>
      </li>

      {/* <button onClick={handleClick}></button> */}
    </div>
  );
}
